### ISSUE TITLE
Build Script

### ISSUE THREAD

**Issue by robertmuehsig** [Sevitec/oneoffixx-connectclient#1]
Erstell ein Build Script - am besten via C# Make

Siehe:
http://blog.codeinside.eu/2016/07/09/cake-building-with-cake/

**Comment by robertmuehsig** [comment]
http://cakebuild.net/api/cake.common.io/ddae1fba/019c34bf
1. Bauen
2. Schritt zippen
   (evtl. gibts aber noch schritte dazwischen)

**Comment by SeverinAmacher** [comment]
Fixed with https://github.com/Sevitec/oneoffixx-connectclient/commit/3583f879d391e759339e8e5069c49e9b6eb4aa65
